version: "3.7"

services:
    mysqlserver:
        container_name: mysqlserver
        image: mysqlserver
        environment:
          - MYSQL_ROOT_PASSWORD=twitter_password  # Set the root login password
          - MYSQL_DATABASE=twitter                # Create a database named 'twitter'
        ports:
          - 3306:3306

    ubuntu_container:
        container_name: ubuntu_container
        image: ubuntu_container
        volumes:
          - ./files:/usr/src/app/files      # Map the folder 'files' to equivalent folder inside container
        stdin_open: true                    # Same as docker run -i
        tty: true                           # Same as docker run -t