version: "3.7"

services:
    mysqlserver:
        container_name: mysqlserver
        image: twitter_mysql_server
        environment:
          - MYSQL_ROOT_PASSWORD=twitter_password
          - MYSQL_DATABASE=twitter
        ports:
            - 3306:3306
        # healthcheck:
        #   test: "/usr/bin/mysql --user=db_engineer --password=twitter_password --execute \"SHOW DATABASES;\""

