version: "3.7"

services:
    mysqlserver:
        image: twitter_mysql_server
        environment:
          - MYSQL_ROOT_PASSWORD=twitter_password
          - MYSQL_DATABASE=twitter
        ports:
          - 3306:3306

    ubuntu_container:
        image: ubuntu_container
        volumes:
          - ./files:/usr/src/app/files      # Map the folder 'files' to equivalent folder inside container
        stdin_open: true # docker run -i
        tty: true        # docker run -t